name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract release name from tag
      id: extract_release_name
      run: |
        RELEASE_NAME=${GITHUB_REF#refs/tags/}
        echo "::set-output name=release_name::$RELEASE_NAME"

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install pnpm
      run: |
        npm install -g pnpm

    - name: Install dependencies
      run: |
        pnpm install

    - name: Run build script
      run: |
        pnpm run build -- ${{ steps.extract_release_name.outputs.release_name }}

    - name: Prepare release assets
      run: |
        mkdir LGF_Loading
        cp -r dist LGF_Loading/
        cp fxmanifest.lua LGF_Loading/
        cp LICENSE LGF_Loading/
        cp README.md LGF_Loading/

    - name: Compress Asset
      run: |
        REPO_NAME=$(basename `git rev-parse --show-toplevel`)
        cd LGF_Loading
        zip -r ../LGF_Loading.zip .

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        tag_name: ${{ steps.extract_release_name.outputs.release_name }}
        release_name: ${{ steps.extract_release_name.outputs.release_name }}
        body: |
          Version Bump to ${{ steps.extract_release_name.outputs.release_name }}.
        draft: true
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./LGF_Loading.zip
        asset_name: LGF_Loading.zip
        asset_content_type: application/zip
